import 'fund_models.dart';

const _hdfcBasis =
    'Direct base expense ratio (BER): includes statutory levies on expenses that form BER; excludes brokerage, transaction costs and execution-related statutory levies. Not directly comparable with SBI BER.';
const _sbiBasis =
    'Direct base expense ratio (BER), excluding GST. SBI TER additionally includes brokerage, transaction costs and statutory levies including GST. Not directly comparable with HDFC BER.';
const _hdfcFactsheet =
    'https://files.hdfcfund.com/s3fs-public/2026-09/HDFC%20MF%20Factsheet%20-%20August%202026.pdf';
const _sbiFactsheet =
    'https://www.sbimf.com/docs/default-source/scheme-factsheets/all-sbimf-schemes-factsheet-august-2026.pdf?sfvrsn=2110e2d5_4';
const _hdfcFlexiMinimum =
    'https://www.hdfcfund.com/explore/mutual-funds//hdfc-flexi-cap-fund/direct';
const _hdfcAggMinimum =
    'https://www.hdfcfund.com/explore/mutual-funds/hdfc-aggressive-hybrid-fund/direct';
const _hdfcCorpMinimum =
    'https://www.hdfcfund.com/explore/mutual-funds/hdfc-corporate-bond-fund/direct';

/// Scheme and portfolio facts disclosed for 31 August 2026.
final List<FundReference> fundCatalog = [
  FundReference(
    schemeCode: '118955',
    name: 'HDFC Flexi Cap Fund',
    amc: 'HDFC Mutual Fund',
    category: 'Flexi Cap',
    expenseRatioPct: 0.67,
    expenseBasis: _hdfcBasis,
    aumCrore: 113606.47,
    minSipPaise: 10000,
    minLumpSumPaise: 10000,
    minimumSourceUrl: _hdfcFlexiMinimum,
    minimumAsOfDate: DateTime(2026, 10, 5),
    manager: 'Amit Ganatra (equity); Bhagyesh Kagalkar (gold/silver)',
    managerExperience: 'Amit Ganatra: over 19 years, managing since 1 February 2026; Bhagyesh Kagalkar: over 31 years, managing gold/silver since 26 August 2026',
    managerOtherFunds: ['HDFC Focused Fund'],
    asOfDate: DateTime(2026, 8, 31),
    sourceUrl: _hdfcFactsheet,
    benchmarkName: 'NIFTY 500 Index (TRI)',
    datedFundReturns: {1: 6.84, 3: 17.63, 5: 18.46},
    datedBenchmarkReturns: {1: 5.31, 3: 12.54, 5: 11.12},
    holdingsDate: DateTime(2026, 8, 31),
    holdingsComplete: false,
    holdings: [
      SecurityWeight(
        id: 'INE090A01021',
        name: 'ICICI Bank Ltd.',
        sector: 'Banks',
        weight: 9.19,
      ),
      SecurityWeight(
        id: 'INE238A01034',
        name: 'Axis Bank Ltd.',
        sector: 'Banks',
        weight: 6.19,
      ),
      SecurityWeight(
        id: 'INE040A01034',
        name: 'HDFC Bank Ltd.',
        sector: 'Banks',
        weight: 5.71,
      ),
      SecurityWeight(
        id: 'INE062A01020',
        name: 'State Bank of India',
        sector: 'Banks',
        weight: 4.16,
      ),
      SecurityWeight(
        id: 'INE758T01015',
        name: 'Eternal Ltd.',
        sector: 'Retailing',
        weight: 3.39,
      ),
      SecurityWeight(
        id: 'INE237A01036',
        name: 'Kotak Mahindra Bank Ltd.',
        sector: 'Banks',
        weight: 3.27,
      ),
      SecurityWeight(
        id: 'INE123W01016',
        name: 'SBI Life Insurance Company Ltd.',
        sector: 'Insurance',
        weight: 3.19,
      ),
      SecurityWeight(
        id: 'INE018A01030',
        name: 'Larsen and Toubro Ltd.',
        sector: 'Construction',
        weight: 3.16,
      ),
      SecurityWeight(
        id: 'INE646L01027',
        name: 'InterGlobe Aviation Ltd.',
        sector: 'Transport Services',
        weight: 2.98,
      ),
      SecurityWeight(
        id: 'INE585B01010',
        name: 'Maruti Suzuki India Ltd.',
        sector: 'Automobiles',
        weight: 2.74,
      ),
    ],
  ),
  FundReference(
    schemeCode: '119718',
    name: 'SBI Flexicap Fund',
    amc: 'SBI Mutual Fund',
    category: 'Flexi Cap',
    expenseRatioPct: 0.72,
    expenseBasis: _sbiBasis,
    aumCrore: 23228.68,
    minSipPaise: 50000,
    minLumpSumPaise: 100000,
    manager: 'Anup Upadhyay',
    managerExperience: '18 years; managing since December 2024',
    managerOtherFunds: [],
    asOfDate: DateTime(2026, 8, 31),
    sourceUrl: _sbiFactsheet,
    benchmarkName: 'BSE 500 TRI',
    datedFundReturns: {1: 4.34, 3: 10.05, 5: 9.10},
    datedBenchmarkReturns: {1: 4.69, 3: 12.08, 5: 10.90},
    holdingsDate: DateTime(2026, 8, 31),
    holdingsComplete: false,
    holdings: [
      SecurityWeight(
        id: 'INE090A01021',
        name: 'ICICI Bank Ltd.',
        sector: 'Banks',
        weight: 7.22,
      ),
      SecurityWeight(
        id: 'INE040A01034',
        name: 'HDFC Bank Ltd.',
        sector: 'Banks',
        weight: 5.55,
      ),
      SecurityWeight(
        id: 'INE018A01030',
        name: 'Larsen and Toubro Ltd.',
        sector: 'Construction',
        weight: 3.86,
      ),
      SecurityWeight(
        id: 'INE917I01010',
        name: 'Bajaj Auto Ltd.',
        sector: 'Automobiles',
        weight: 3.85,
      ),
      SecurityWeight(
        id: 'INE591G01025',
        name: 'Coforge Ltd.',
        sector: 'IT - Software',
        weight: 2.97,
      ),
      SecurityWeight(
        id: 'INE406A01037',
        name: 'Aurobindo Pharma Ltd.',
        sector: 'Pharmaceuticals & Biotechnology',
        weight: 2.96,
      ),
      SecurityWeight(
        id: 'INE066A01021',
        name: 'Eicher Motors Ltd.',
        sector: 'Automobiles',
        weight: 2.60,
      ),
      SecurityWeight(
        id: 'INE880J01026',
        name: 'JSW Infrastructure Ltd.',
        sector: 'Transport Infrastructure',
        weight: 2.55,
      ),
      SecurityWeight(
        id: 'INE062A01020',
        name: 'State Bank of India',
        sector: 'Banks',
        weight: 2.28,
      ),
      SecurityWeight(
        id: 'INE280A01028',
        name: 'Titan Company Ltd.',
        sector: 'Consumer Durables',
        weight: 2.21,
      ),
    ],
  ),
  FundReference(
    schemeCode: '118987',
    name: 'HDFC Corporate Bond Fund',
    amc: 'HDFC Mutual Fund',
    category: 'Corporate Bond',
    expenseRatioPct: 0.38,
    expenseBasis: _hdfcBasis,
    aumCrore: 30286.08,
    minSipPaise: 10000,
    minLumpSumPaise: 10000,
    minimumSourceUrl: _hdfcCorpMinimum,
    minimumAsOfDate: DateTime(2026, 10, 5),
    manager: 'Anupam Joshi',
    managerExperience: 'Over 20 years; managing since 27 October 2022',
    managerOtherFunds: [
      'HDFC Medium Term Fund',
      'HDFC Banking and PSU Debt Fund',
      'HDFC Gilt Fund',
    ],
    asOfDate: DateTime(2026, 8, 31),
    sourceUrl: _hdfcFactsheet,
    benchmarkName: 'NIFTY Corporate Bond Index A-II',
    datedFundReturns: {1: 5.14, 3: 7.15, 5: 6.30},
    datedBenchmarkReturns: {1: 4.27, 3: 6.46, 5: 5.63},
  ),
  FundReference(
    schemeCode: '146215',
    name: 'SBI Corporate Bond Fund',
    amc: 'SBI Mutual Fund',
    category: 'Corporate Bond',
    expenseRatioPct: 0.31,
    expenseBasis: _sbiBasis,
    aumCrore: 22120.98,
    minSipPaise: 100000,
    minLumpSumPaise: 500000,
    manager: 'Rajeev Radhakrishnan; Ardhendu Bhattacharya',
    managerExperience: 'Rajeev: 24 years, since January 2019; Ardhendu: 15 years, since December 2023',
    managerOtherFunds: ['SBI Aggressive Hybrid Fund'],
    asOfDate: DateTime(2026, 8, 31),
    sourceUrl: _sbiFactsheet,
    benchmarkName: 'NIFTY Corporate Bond Index A-II',
    datedFundReturns: {1: 5.45, 3: 7.30, 5: 6.29},
    datedBenchmarkReturns: {1: 4.27, 3: 6.46, 5: 5.63},
  ),
  FundReference(
    schemeCode: '119062',
    name: 'HDFC Aggressive Hybrid Fund',
    amc: 'HDFC Mutual Fund',
    category: 'Aggressive Hybrid',
    expenseRatioPct: 1.06,
    expenseBasis: _hdfcBasis,
    aumCrore: 22296.62,
    minSipPaise: 10000,
    minLumpSumPaise: 10000,
    minimumSourceUrl: _hdfcAggMinimum,
    minimumAsOfDate: DateTime(2026, 10, 5),
    manager: 'Anupam Joshi (debt); Srinivasan Ramamurthy (equity); Bhagyesh Kagalkar (gold/silver)',
    managerExperience: 'Anupam: over 20 years, since 6 October 2022; Srinivasan: over 19 years, since 1 July 2025; Bhagyesh: over 31 years, since 26 August 2026',
    managerOtherFunds: [
      'HDFC Corporate Bond Fund',
      'HDFC Flexi Cap Fund',
      'HDFC Retirement Fund - Equity Plan',
    ],
    asOfDate: DateTime(2026, 8, 31),
    sourceUrl: _hdfcFactsheet,
    benchmarkName: 'NIFTY 50 Hybrid Composite Debt 65:35 Index (TRI)',
    datedFundReturns: {1: -0.72, 3: 7.68, 5: 9.06},
    datedBenchmarkReturns: {1: 0.89, 3: 8.09, 5: 7.46},
    holdingsDate: DateTime(2026, 8, 31),
    holdingsComplete: false,
    holdings: [
      SecurityWeight(
        id: 'INE090A01021',
        name: 'ICICI Bank Ltd.',
        sector: 'Banks',
        weight: 7.17,
      ),
      SecurityWeight(
        id: 'INE040A01034',
        name: 'HDFC Bank Ltd.',
        sector: 'Banks',
        weight: 6.00,
      ),
      SecurityWeight(
        id: 'INE002A01018',
        name: 'Reliance Industries Ltd.',
        sector: 'Petroleum Products',
        weight: 4.24,
      ),
      SecurityWeight(
        id: 'INE237A01036',
        name: 'Kotak Mahindra Bank Ltd.',
        sector: 'Banks',
        weight: 3.29,
      ),
      SecurityWeight(
        id: 'INE238A01034',
        name: 'Axis Bank Ltd.',
        sector: 'Banks',
        weight: 3.21,
      ),
      SecurityWeight(
        id: 'INE062A01020',
        name: 'State Bank of India',
        sector: 'Banks',
        weight: 3.00,
      ),
      SecurityWeight(
        id: 'INE018A01030',
        name: 'Larsen and Toubro Ltd.',
        sector: 'Construction',
        weight: 2.19,
      ),
      SecurityWeight(
        id: 'INE009A01021',
        name: 'Infosys Ltd.',
        sector: 'IT - Software',
        weight: 2.03,
      ),
      SecurityWeight(
        id: 'INE361B01024',
        name: "Divi's Laboratories Ltd.",
        sector: 'Pharmaceuticals & Biotechnology',
        weight: 2.02,
      ),
      SecurityWeight(
        id: 'INE397D01024',
        name: 'Bharti Airtel Ltd.',
        sector: 'Telecom - Services',
        weight: 1.95,
      ),
    ],
  ),
  FundReference(
    schemeCode: '119609',
    name: 'SBI Aggressive Hybrid Fund',
    amc: 'SBI Mutual Fund',
    category: 'Aggressive Hybrid',
    expenseRatioPct: 0.55,
    expenseBasis: _sbiBasis,
    aumCrore: 88692.67,
    minSipPaise: 50000,
    minLumpSumPaise: 100000,
    manager: 'R. Srinivasan (equity); Rajeev Radhakrishnan (debt)',
    managerExperience: 'R. Srinivasan: 33 years, since January 2012; Rajeev Radhakrishnan: 24 years, since November 2023',
    managerOtherFunds: ['SBI Corporate Bond Fund'],
    asOfDate: DateTime(2026, 8, 31),
    sourceUrl: _sbiFactsheet,
    benchmarkName: 'CRISIL Hybrid 35+65 - Aggressive Index',
    datedFundReturns: {1: 8.44, 3: 13.50, 5: 10.62},
    datedBenchmarkReturns: {1: 4.32, 3: 10.13, 5: 8.95},
    holdingsDate: DateTime(2026, 8, 31),
    holdingsComplete: false,
    holdings: [
      SecurityWeight(
        id: 'INE062A01020',
        name: 'State Bank of India',
        sector: 'Banks',
        weight: 4.53,
      ),
      SecurityWeight(
        id: 'INE090A01021',
        name: 'ICICI Bank Ltd.',
        sector: 'Banks',
        weight: 4.43,
      ),
      SecurityWeight(
        id: 'INE343H01029',
        name: 'Solar Industries India Ltd.',
        sector: 'Chemicals & Petrochemicals',
        weight: 4.06,
      ),
      SecurityWeight(
        id: 'INE814H01029',
        name: 'Adani Power Ltd.',
        sector: 'Power',
        weight: 4.02,
      ),
      SecurityWeight(
        id: 'INE237A01036',
        name: 'Kotak Mahindra Bank Ltd.',
        sector: 'Banks',
        weight: 3.31,
      ),
      SecurityWeight(
        id: 'INE414G01012',
        name: 'Muthoot Finance Ltd.',
        sector: 'Finance',
        weight: 3.19,
      ),
      SecurityWeight(
        id: 'INE931S01010',
        name: 'Adani Energy Solutions Ltd.',
        sector: 'Power',
        weight: 3.04,
      ),
      SecurityWeight(
        id: 'INE296A01032',
        name: 'Bajaj Finance Ltd.',
        sector: 'Finance',
        weight: 2.80,
      ),
    ],
  ),
];
